---
name: reverse-proxy
services:
  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    networks:
      - proxy-frontend
      - proxy-backend
    environment:
      # Postgres parameters:
      DB_POSTGRES_HOST: 'proxy-manager-db'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'npm'
      DB_POSTGRES_PASSWORD: 'npmpass'
      DB_POSTGRES_NAME: 'npm'
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
      #INITIAL_ADMIN_EMAIL: marcos.donato@fatec.sp.gov.br
      #INITIAL_ADMIN_PASSWORD: @lunoFat3c
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - proxy-manager-db
    restart: unless-stopped

  proxy-manager-db:
    image: postgres:latest
    networks:
      - proxy-backend
    environment:
      POSTGRES_USER: 'npm'
      POSTGRES_PASSWORD: 'npmpass'
      POSTGRES_DB: 'npm'
      #INITIAL_ADMIN_EMAIL: marcos.donato@fatec.sp.gov.br
      #INITIAL_ADMIN_PASSWORD: @lunoFat3c
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  proxy-frontend:
    name: proxy-frontend
    driver: bridge
    attachable: true
  proxy-backend:
    name: proxy-backend
    driver: bridge

volumes:
  npm_data:
    name: npm_data
  npm_letsencrypt:
    name: npm_letsencrypt
  postgres:
    name: postgres

